export type SiteLanguage = 'en' | 'af';

const STORAGE_KEY = 'vermicompostfarm-language';

const afrikaans: Record<string, string> = {
  'Skip to content': 'Spring na inhoud',
  'Vermicompost Farm home': 'Vermicompost Farm-tuisblad',
  'Primary navigation': 'Hoofnavigasie',
  'Mobile navigation': 'Mobiele navigasie',
  'Language': 'Taal',
  'Shop': 'Winkel',
  'Learn': 'Leer',
  'Our Farm': 'Ons Plaas',
  'Contact': 'Kontak',
  'Enquiry': 'Navraag',
  'Menu': 'Kieslys',
  'Products': 'Produkte',
  'Visit the farm': 'Besoek die plaas',
  'Living soil products, made naturally in Pretoria.': 'Lewende grondprodukte, natuurlik gemaak in Pretoria.',
  'Find your way': 'Vind jou pad',
  'Visit & contact': 'Besoek & kontak',
  'How ordering works': 'Hoe bestellings werk',
  'Privacy': 'Privaatheid',
  'Pretoria, South Africa': 'Pretoria, Suid-Afrika',
  '· Pretoria, South Africa': '· Pretoria, Suid-Afrika',
  'Rows of working worm bins at Vermicompost Farm': 'Rye werkende wurmbakke by Vermicompost Farm',
  'Rows of vermicomposting beds on the farm': 'Rye vermikomposbeddings op die plaas',
  'Added to your enquiry.': 'By jou navraag gevoeg.',
  'Review enquiry': 'Hersien navraag',
  'Add': 'Voeg by',
  'All products': 'Alle produkte',
  'Vermicompost Farm · Pretoria': 'Vermicompost Farm · Pretoria',
  'Good things\ngrow from soil.': 'Goeie dinge\ngroei uit grond.',
  'Vermicompost\n100% Organic': 'Vermikompos\n100% Organies',
  'Earthworm-powered compost, living microbes and honest soil care—made slowly, naturally and right here on the farm.': 'Kompos deur erdwurms, lewende mikrobes en eerlike grondversorging—stadig, natuurlik en hier op die plaas gemaak.',
  'Shop farm products': 'Koop plaasprodukte',
  'Watch the full farm film': 'Kyk na die volledige plaasvideo',
  'Scroll to dig deeper': 'Rol af om meer te ontdek',
  'From the farm': 'Van die plaas',
  'A few good things for better soil.': '’n Paar goeie dinge vir beter grond.',
  'Farm-made compost, worms and liquid plant food for gardens of every size.': 'Plaasgemaakte kompos, wurms en vloeibare plantvoeding vir tuine van elke grootte.',
  'See all products →': 'Sien alle produkte →',
  'Why vermicompost': 'Waarom vermikompos',
  'Healthy soil is alive.': 'Gesonde grond lewe.',
  'Red wigglers turn prepared organic matter into a gentle, microbe-rich soil conditioner. A little goes a long way in pots, beds and new planting.': 'Rooi komposwurms verander voorbereide organiese materiaal in ’n sagte, mikrobe-ryke grondverbeteraar. ’n Klein bietjie gaan ver in potte, beddings en nuwe aanplantings.',
  'Gentle nutrition': 'Sagte voeding',
  'Steady plant nutrition in a natural form.': 'Bestendige plantvoeding in ’n natuurlike vorm.',
  'Better structure': 'Beter struktuur',
  'Helps soil balance drainage and moisture.': 'Help grond om dreinering en vog te balanseer.',
  'Living biology': 'Lewende biologie',
  'Adds beneficial organisms to the root zone.': 'Voeg voordelige organismes by die wortelsone.',
  'How the farm works': 'Hoe die plaas werk',
  'Visit or get in touch': 'Besoek of kontak ons',
  'Collect from the farm in Pretoria.': 'Haal by die plaas in Pretoria af.',
  'Send Nico a message to check availability, arrange collection or ask about local delivery.': 'Stuur vir Nico ’n boodskap om beskikbaarheid na te gaan, afhaal te reël of oor plaaslike aflewering te vra.',
  'WhatsApp Nico ↗': 'WhatsApp vir Nico ↗',
  'Contact details and directions →': 'Kontakbesonderhede en aanwysings →',
  'The farm shop': 'Die plaaswinkel',
  'Living products for living soil.': 'Lewende produkte vir lewende grond.',
  'Choose what you need and send an enquiry. Nico will confirm availability, collection and local delivery.': 'Kies wat jy nodig het en stuur ’n navraag. Nico sal beskikbaarheid, afhaal en plaaslike aflewering bevestig.',
  'product': 'produk',
  'products': 'produkte',
  'Compost & soil': 'Kompos & grond',
  'Compost & soil products': 'Kompos- & grondprodukte',
  'Finished vermicompost and soil-building blends.': 'Voltooide vermikompos en mengsels wat grond opbou.',
  'Worms & supplies': 'Wurms & benodigdhede',
  'Worms & care': 'Wurms & versorging',
  'Everything needed to start or support a worm farm.': 'Alles wat nodig is om ’n wurmplaas te begin of te versorg.',
  'Liquid plant food': 'Vloeibare plantvoeding',
  'Liquids': 'Vloeistowwe',
  'Fresh biological support for soil and foliage.': 'Vars biologiese ondersteuning vir grond en blare.',
  'Farm experiences': 'Plaaservarings',
  'See the process and learn from a working farm.': 'Sien die proses en leer by ’n werkende plaas.',
  'Large quantities': 'Groot hoeveelhede',
  'Need a cubic metre or more?': 'Benodig jy ’n kubieke meter of meer?',
  'Tell us what you are planting, how much you need and where it needs to go. We’ll confirm a sensible collection or delivery option.': 'Vertel ons wat jy plant, hoeveel jy nodig het en waarheen dit moet gaan. Ons sal ’n praktiese afhaal- of afleweringsopsie bevestig.',
  'Start a bulk enquiry': 'Begin ’n grootmaatnavraag',
  'Sifted vermicompost': 'Gesifte vermikompos',
  'Fine, mature worm castings—our concentrated “black gold” for gardens and containers.': 'Fyn, volwasse wurmmis—ons gekonsentreerde “swart goud” vir tuine en houers.',
  'Unsifted vermicompost': 'Ongesifte vermikompos',
  'A rustic, economical farm blend with castings and partly processed organic matter.': '’n Rustieke, ekonomiese plaasmengsel met wurmmis en gedeeltelik verwerkte organiese materiaal.',
  'Potting soil': 'Potgrond',
  'A balanced growing medium enriched with living vermicompost.': '’n Gebalanseerde groeimedium verryk met lewende vermikompos.',
  'Organic mulch': 'Organiese deklaag',
  'Natural surface cover that protects soil and reduces moisture loss.': 'Natuurlike grondbedekking wat die grond beskerm en vogverlies verminder.',
  'Aged horse manure': 'Verouderde perdemis',
  'Well-aged organic matter for improving beds and feeding long-term soil fertility.': 'Goed verouderde organiese materiaal om beddings te verbeter en grondvrugbaarheid op lang termyn te voed.',
  'Red wiggler worms': 'Rooi komposwurms',
  'A lively starter colony of Eisenia fetida in familiar, established bedding.': '’n Lewendige beginkolonie Eisenia fetida in bekende, gevestigde beddegoed.',
  'Worm bedding & food': 'Wurmbeddegoed & kos',
  'Pre-composted horse manure and wood shavings prepared for hungry composting worms.': 'Vooraf gekomposteerde perdemis en houtskaafsels, voorberei vir honger komposwurms.',
  'Vermicompost tea': 'Vermikompostee',
  'Fresh, aerated liquid carrying nutrients and beneficial microorganisms.': 'Vars, deurlugte vloeistof wat voedingstowwe en voordelige mikro-organismes dra.',
  'Worm farm information tour': 'Wurmplaas-inligtingstoer',
  'A practical 30-minute introduction to worms, vermicompost and the farm process.': '’n Praktiese 30-minute-inleiding tot wurms, vermikompos en die plaasproses.',
  'Enquire': 'Doen navraag',
  'Price on enquiry': 'Prys op navraag',
  'From R85': 'Vanaf R85',
  'From R10': 'Vanaf R10',
  'From': 'Vanaf',
  '25 dm³ bag': '25 dm³-sak',
  '60 dm³ bag': '60 dm³-sak',
  '1 m³ bulk': '1 m³-grootmaat',
  'Bulk order—delivery confirmed separately': 'Grootmaatbestelling—aflewering word afsonderlik bevestig',
  'Populated starter tray': 'Bevolkte beginbak',
  'Standard bag': 'Standaardsak',
  'Price confirmed on enquiry': 'Prys word met navraag bevestig',
  'Per litre': 'Per liter',
  '5 litre container': '5-liter-houer',
  '30-minute tour · per person': '30-minute-toer · per persoon',
  'Home': 'Tuis',
  'Choose an option': 'Kies ’n opsie',
  'Add to enquiry': 'Voeg by navraag',
  'Collection or local delivery by arrangement': 'Afhaal of plaaslike aflewering volgens reëling',
  'Collection recommended': 'Afhaal word aanbeveel',
  'Collection by arrangement': 'Afhaal volgens reëling',
  'Fresh batches—confirm before collection': 'Vars sarsies—bevestig voor afhaal',
  'Advance booking required': 'Voorafbespreking is nodig',
  'Why it works': 'Waarom dit werk',
  'Built by biology,': 'Deur biologie gebou,',
  'not a factory.': 'nie deur ’n fabriek nie.',
  'A good way to use it': '’n Goeie manier om dit te gebruik',
  'Natural products vary from batch to batch. Ask the farm if you are unsure about a specific plant or application.': 'Natuurlike produkte verskil van sarsie tot sarsie. Vra die plaas indien jy onseker is oor ’n spesifieke plant of toepassing.',
  'Red wigglers transform pre-composted horse manure and wood shavings into a rich, stable soil conditioner over roughly ten weeks.': 'Rooi komposwurms verander vooraf gekomposteerde perdemis en houtskaafsels oor ongeveer tien weke in ’n ryk, stabiele grondverbeteraar.',
  'The sifted finish is easy to mix into potting soil, top-dress garden beds or apply gently around established plants.': 'Die gesifte produk meng maklik met potgrond en kan as ’n bolaag op tuinbeddings of liggies rondom gevestigde plante gebruik word.',
  'Unsifted vermicompost retains more texture and organic matter than the fine sifted product.': 'Ongesifte vermikompos behou meer tekstuur en organiese materiaal as die fyn gesifte produk.',
  'It is an excellent choice for beds, trees, larger landscape areas and gardeners who value bulk soil improvement.': 'Dit is ’n uitstekende keuse vir beddings, bome, groter landskapareas en tuiniers wat grond in grootmaat wil verbeter.',
  'Our potting soil combines structure, drainage and the biological benefits of vermicompost.': 'Ons potgrond kombineer struktuur, dreinering en die biologiese voordele van vermikompos.',
  'Use it for containers, seedlings, herbs and ornamental plants.': 'Gebruik dit vir houers, saailinge, kruie en sierplante.',
  'A practical farm mulch for beds, trees and pathways.': '’n Praktiese plaasdeklaag vir beddings, bome en paadjies.',
  'Mulch moderates soil temperature, discourages weeds and feeds the soil as it breaks down.': 'Deklaag matig grondtemperatuur, onderdruk onkruid en voed die grond soos dit afbreek.',
  'Aged horse manure is a valuable source of organic matter for beds, orchards and landscape projects.': 'Verouderde perdemis is ’n waardevolle bron van organiese materiaal vir beddings, boorde en landskapprojekte.',
  'It is the same foundational farm material used in our worm bedding process.': 'Dit is dieselfde basiese plaasmateriaal wat in ons wurmbeddegoedproses gebruik word.',
  'We sell red wigglers as a populated tray rather than counting or weighing individual worms.': 'Ons verkoop rooi komposwurms as ’n bevolkte bak eerder as om individuele wurms te tel of te weeg.',
  'Each tray spends at least five days on an operational bin so you receive worms of varied sizes in the bedding they know.': 'Elke bak bring minstens vyf dae op ’n werkende bak deur, sodat jy wurms van verskillende groottes in hul bekende beddegoed ontvang.',
  'The same bedding and food mixture used throughout our production farm.': 'Dieselfde beddegoed- en voedselmengsel wat oral op ons produksieplaas gebruik word.',
  'It is pre-composted for several weeks, giving worms a safe, familiar material to settle into.': 'Dit word etlike weke vooraf gekomposteer en gee die wurms ’n veilige, bekende materiaal om in te vestig.',
  'Vermicompost tea is brewed from castings in clean, chemical-free water and actively aerated.': 'Vermikompostee word van wurmmis in skoon, chemikalievrye water gebrou en aktief deurlug.',
  'It is best used very fresh. For the strongest results, we also teach customers how to brew their own on site.': 'Dit werk die beste wanneer dit baie vars gebruik word. Vir die beste resultate leer ons klante ook hoe om hul eie tee op die plaas te brou.',
  'Walk through the working farm with Nico and see how bedding, bins, red wigglers and sifting come together.': 'Stap saam met Nico deur die werkende plaas en sien hoe beddegoed, bakke, rooi komposwurms en sifting saamwerk.',
  'Tours are arranged in advance and work well for individuals, gardening groups and curious families.': 'Toere word vooraf gereël en is geskik vir individue, tuinmaakgroepe en nuuskierige gesinne.',
  'Mix a handful into planting holes.': 'Meng ’n handvol in plantgate.',
  'Top-dress pot plants monthly.': 'Gee potplante maandeliks ’n bolaag.',
  'Blend into garden soil or potting mixes.': 'Meng dit met tuingrond of potgrondmengsels.',
  'Work into new garden beds.': 'Werk dit in nuwe tuinbeddings in.',
  'Spread beneath mulch around trees.': 'Strooi dit onder deklaag rondom bome.',
  'Use when preparing larger growing areas.': 'Gebruik dit wanneer groter groeiareas voorberei word.',
  'Fill clean pots and containers.': 'Vul skoon potte en houers.',
  'Refresh tired container soil.': 'Verfris uitgeputte grond in houers.',
  'Use for transplanting seedlings.': 'Gebruik dit wanneer saailinge uitgeplant word.',
  'Apply 5–8 cm deep.': 'Dien dit 5–8 cm diep toe.',
  'Keep mulch clear of plant stems.': 'Hou deklaag weg van plantstingels.',
  'Refresh as the layer decomposes.': 'Vul dit aan soos die laag ontbind.',
  'Incorporate before planting.': 'Werk dit in voordat jy plant.',
  'Layer into compost systems.': 'Voeg dit in lae by komposstelsels.',
  'Use beneath a finished mulch layer.': 'Gebruik dit onder ’n voltooide deklaag.',
  'Prepare a shaded, well-drained worm farm.': 'Berei ’n skaduryke, goed gedreineerde wurmplaas voor.',
  'Add the entire tray, including bedding.': 'Voeg die hele bak, insluitend beddegoed, by.',
  'Keep moist like a wrung-out sponge.': 'Hou dit so klam soos ’n uitgedrukte spons.',
  'Add as fresh bedding or food.': 'Voeg dit as vars beddegoed of kos by.',
  'Moisten before use if needed.': 'Maak dit klam voor gebruik indien nodig.',
  'Avoid compacting the material.': 'Moenie die materiaal verdig nie.',
  'Apply to soil or as a foliar spray.': 'Dien dit op die grond of as ’n blaarbespuiting toe.',
  'Use promptly after collection.': 'Gebruik dit kort ná afhaal.',
  'Repeat every two weeks during active growth.': 'Herhaal elke twee weke gedurende aktiewe groei.',
  'Choose your preferred date in the enquiry note.': 'Kies jou voorkeurdatum in die navraagnota.',
  'Wear practical closed shoes.': 'Dra praktiese, toe skoene.',
  'Allow time to browse products after the tour.': 'Laat tyd toe om ná die toer deur produkte te blaai.',
  'Slow-release plant nutrition': 'Stadigvrystellende plantvoeding',
  'Living beneficial microbes': 'Lewende voordelige mikrobes',
  'Improved water holding and aeration': 'Verbeterde waterhouvermoë en belugting',
  'Safe around children and pets': 'Veilig rondom kinders en troeteldiere',
  'Cost-effective organic matter': 'Kostedoeltreffende organiese materiaal',
  'Improves soil structure': 'Verbeter grondstruktuur',
  'Adds slow-release fertility': 'Voeg stadigvrystellende vrugbaarheid by',
  'Ready-to-use mix': 'Gereed-vir-gebruik-mengsel',
  'Good moisture balance': 'Goeie vogbalans',
  'Biologically active': 'Biologies aktief',
  'Reduces evaporation': 'Verminder verdamping',
  'Protects soil life': 'Beskerm grondlewe',
  'Suppresses weeds': 'Onderdruk onkruid',
  'Builds organic matter': 'Bou organiese materiaal op',
  'Improves soil texture': 'Verbeter grondtekstuur',
  'Supports soil organisms': 'Ondersteun grondorganismes',
  'Established mixed-age colony': 'Gevestigde kolonie van gemengde ouderdomme',
  'Transported in familiar bedding': 'Vervoer in bekende beddegoed',
  'Ideal for home worm farms': 'Ideaal vir tuiswurmplase',
  'Farm-tested blend': 'Plaasgetoetste mengsel',
  'Food and habitat in one': 'Kos en habitat in een',
  'Useful for new and established systems': 'Nuttig vir nuwe en gevestigde stelsels',
  'Microbe-rich liquid': 'Mikrobe-ryke vloeistof',
  'Suitable for most garden plants': 'Geskik vir die meeste tuinplante',
  'See a working system': 'Sien ’n werkende stelsel',
  'Ask practical questions': 'Vra praktiese vrae',
  'Learn before starting at home': 'Leer voordat jy tuis begin',
  'Keep exploring': 'Ontdek meer',
  'More from the farm.': 'Meer van die plaas.',
  'Products that work naturally alongside this one.': 'Produkte wat natuurlik saam met hierdie een werk.',
  'Practical guides': 'Praktiese gidse',
  'Simple ways to work with living soil.': 'Eenvoudige maniere om met lewende grond te werk.',
  'Short, practical notes from a working worm farm.': 'Kort, praktiese notas van ’n werkende wurmplaas.',
  'Read the guide →': 'Lees die gids →',
  'Using vermicompost': 'Hoe om vermikompos te gebruik',
  'Simple, safe ways to put black gold to work in pots, beds and planting holes.': 'Eenvoudige, veilige maniere om swart goud in potte, beddings en plantgate te gebruik.',
  'Starting a worm farm': 'Begin ’n wurmplaas',
  'Create a cool, moist and well-fed home for red wigglers.': 'Skep ’n koel, klam en goed gevoede tuiste vir rooi komposwurms.',
  'Brewing vermicompost tea': 'Brou vermikompostee',
  'A practical recipe for a fresh, aerated microbial garden tonic.': '’n Praktiese resep vir ’n vars, deurlugte mikrobiese tuintonikum.',
  'Need practical help?': 'Benodig jy praktiese hulp?',
  'Bring your questions to the farm.': 'Bring jou vrae na die plaas.',
  'Ask Nico about your garden, worm bin or soil problem—or arrange a short farm tour.': 'Vra vir Nico oor jou tuin, wurmbak of grondprobleem—of reël ’n kort plaastoer.',
  'Contact the farm': 'Kontak die plaas',
  'Field notes': 'Veldnotas',
  'Practical guide': 'Praktiese gids',
  '· Practical guide': '· Praktiese gids',
  'In this guide': 'In hierdie gids',
  'Put it into practice': 'Pas dit prakties toe',
  'Products for this guide.': 'Produkte vir hierdie gids.',
  'Farm-made materials to help you get started with confidence.': 'Plaasgemaakte materiaal om jou met vertroue aan die gang te kry.',
  'Why gardeners use it': 'Waarom tuiniers dit gebruik',
  'For pots and containers': 'Vir potte en houers',
  'For beds and planting': 'Vir beddings en aanplanting',
  'Choose the right home': 'Kies die regte tuiste',
  'Settle the colony': 'Vestig die kolonie',
  'Feed and observe': 'Voer en neem waar',
  'What you need': 'Wat jy nodig het',
  'Brew for 24 hours': 'Brou vir 24 uur',
  'Use it fresh': 'Gebruik dit vars',
  'Worm castings are concentrated, biologically active and gentle enough for almost every part of the garden. A little really does go a long way.': 'Wurmmis is gekonsentreerd, biologies aktief en sag genoeg vir byna elke deel van die tuin. ’n Klein bietjie gaan werklik ver.',
  'Vermicompost adds nutrients in slow-release organic forms and introduces beneficial microbes that support plant growth.': 'Vermikompos voeg voedingstowwe in stadigvrystellende organiese vorms by en bring voordelige mikrobes in wat plantgroei ondersteun.',
  'It improves aeration and water-holding capacity while helping long-term soil fertility.': 'Dit verbeter belugting en waterhouvermoë terwyl dit grondvrugbaarheid op lang termyn ondersteun.',
  'Mix roughly one part vermicompost into four parts potting medium.': 'Meng ongeveer een deel vermikompos met vier dele potgrondmedium.',
  'For established pots, add a small handful as a monthly top dressing.': 'Voeg vir gevestigde potte maandeliks ’n klein handvol as bolaag by.',
  'Water normally after applying.': 'Gee normaalweg water ná toediening.',
  'Blend a handful into each planting hole.': 'Meng ’n handvol in elke plantgat.',
  'Spread a thin layer around established plants without piling it against stems.': 'Strooi ’n dun laag rondom gevestigde plante sonder om dit teen stingels op te hoop.',
  'Cover with mulch to protect moisture and soil life.': 'Bedek met deklaag om vog en grondlewe te beskerm.',
  'A worm farm is less about complicated equipment and more about creating stable conditions: air, moisture, shade, bedding and regular food.': '’n Wurmplaas gaan minder oor ingewikkelde toerusting en meer oor stabiele toestande: lug, vog, skadu, beddegoed en gereelde kos.',
  'Use a ventilated container with good drainage and keep it out of direct sun. Red wigglers prefer moderate temperatures and darkness.': 'Gebruik ’n geventileerde houer met goeie dreinering en hou dit uit direkte sonlig. Rooi komposwurms verkies matige temperature en donkerte.',
  'Prepare damp bedding with the texture of a wrung-out sponge.': 'Berei klam beddegoed met die tekstuur van ’n uitgedrukte spons voor.',
  'Add the entire populated tray, including its established bedding.': 'Voeg die hele bevolkte bak, insluitend die gevestigde beddegoed, by.',
  'Leave the worms undisturbed for several days before feeding heavily.': 'Laat die wurms vir etlike dae ongestoord voordat jy hulle baie voer.',
  'Add small amounts of chopped fruit and vegetable scraps.': 'Voeg klein hoeveelhede gekapte vrugte- en groentereste by.',
  'Bury food beneath bedding and wait until most is eaten before adding more.': 'Begrawe kos onder die beddegoed en wag totdat die meeste geëet is voordat jy meer byvoeg.',
  'If the bin smells, reduce food and improve airflow.': 'As die bak ruik, verminder die kos en verbeter lugvloei.',
  'Vermicompost tea is most valuable when it is brewed cleanly, actively aerated and used immediately.': 'Vermikompostee is die waardevolste wanneer dit skoon gebrou, aktief deurlug en onmiddellik gebruik word.',
  'A clean 20 litre bucket of non-chlorinated water.': '’n Skoon 20-liter-emmer met ongechloreerde water.',
  'Two cups of quality vermicompost in porous cloth.': 'Twee koppies gehaltevermicompos in poreuse lap.',
  'An aquarium air pump and airstone.': '’n Akwariumlugpomp en lugsteen.',
  'One tablespoon of unsulphured blackstrap molasses; optional kelp or fish fertiliser.': 'Een eetlepel ongeswawelde swartbandmelasse; opsionele kelp- of vismisstof.',
  'Place the vermicompost bag and airstone into the water, add the microbial food and aerate continuously for about 24 hours.': 'Plaas die vermikompossak en lugsteen in die water, voeg die mikrobiese voedsel by en belug aanhoudend vir ongeveer 24 uur.',
  'Do not keep brewing once the tea develops a bad smell. Fresh, healthy tea should smell earthy.': 'Moenie aanhou brou wanneer die tee sleg begin ruik nie. Vars, gesonde tee behoort aards te ruik.',
  'Apply within four hours of finishing the brew.': 'Dien dit binne vier uur ná voltooiing van die brousel toe.',
  'Use undiluted or dilute up to 1:10.': 'Gebruik dit onverdund of verdun tot 1:10.',
  'Water the soil or apply as a fine foliar spray.': 'Gee die grond water of dien dit as ’n fyn blaarbespuiting toe.',
  'Repeat roughly every two weeks when plants are actively growing.': 'Herhaal ongeveer elke twee weke wanneer plante aktief groei.',
  'Our farm': 'Ons plaas',
  'Small farm. Millions of workers.': 'Klein plaas. Miljoene werkers.',
  'Red wigglers quietly turn local organic material into healthier soil.': 'Rooi komposwurms verander plaaslike organiese materiaal stilweg in gesonder grond.',
  'Made in Montana, Pretoria': 'Gemaak in Montana, Pretoria',
  'We let nature do the complicated part.': 'Ons laat die natuur die ingewikkelde deel doen.',
  'Vermicompost Farm produces castings made by red wigglers—Eisenia fetida—with a small amount of stable organic matter.': 'Vermicompost Farm vervaardig wurmmis deur rooi komposwurms—Eisenia fetida—met ’n klein hoeveelheid stabiele organiese materiaal.',
  'Horse manure and wood shavings are prepared before being fed to the worms. Over roughly ten weeks, they become nutrient-rich vermicast: a natural soil conditioner gardeners often call black gold.': 'Perdemis en houtskaafsels word voorberei voordat dit aan die wurms gevoer word. Oor ongeveer tien weke word dit voedingryke vermikompos: ’n natuurlike grondverbeteraar wat tuiniers dikwels swart goud noem.',
  'From organic matter to vermicompost': 'Van organiese materiaal tot vermikompos',
  'Prepare': 'Berei voor',
  'Local organic material is pre-composted until it is ready for the worms.': 'Plaaslike organiese materiaal word vooraf gekomposteer totdat dit gereed is vir die wurms.',
  'Let the worms work': 'Laat die wurms werk',
  'Red wigglers transform it into stable, microbe-rich castings.': 'Rooi komposwurms verander dit in stabiele, mikrobe-ryke wurmmis.',
  'Sift': 'Sif',
  'The finished compost is sifted into a fine, useful soil conditioner.': 'Die voltooide kompos word tot ’n fyn, bruikbare grondverbeteraar gesif.',
  'The working worm beds': 'Die werkende wurmbeddings',
  'Fine sifting': 'Fyn sifting',
  'See it for yourself': 'Kom kyk self',
  'Visit the working farm.': 'Besoek die werkende plaas.',
  'Plan a visit': 'Beplan ’n besoek',
  'Visit and contact': 'Besoek en kontak',
  'Talk to the farm.': 'Praat met die plaas.',
  'Ask a product question, arrange collection or book a short information tour.': 'Vra ’n produkvraag, reël afhaal of bespreek ’n kort inligtingstoer.',
  'Open directions ↗': 'Maak aanwysings oop ↗',
  'Contact Nico': 'Kontak vir Nico',
  'Send a WhatsApp ↗': 'Stuur ’n WhatsApp ↗',
  'Collection': 'Afhaal',
  'Contact Nico before travelling so your order can be prepared.': 'Kontak vir Nico voordat jy ry sodat jou bestelling voorberei kan word.',
  'Local delivery': 'Plaaslike aflewering',
  'Send your suburb and quantity. Availability and cost are confirmed personally.': 'Stuur jou voorstad en hoeveelheid. Beskikbaarheid en koste word persoonlik bevestig.',
  'Farm tours': 'Plaastoere',
  'Thirty-minute information tours are R250 per person and booked in advance.': 'Dertig-minute-inligtingstoere kos R250 per persoon en word vooraf bespreek.',
  'Order enquiry': 'Bestellingsnavraag',
  'Gather what you need. We’ll confirm the rest.': 'Kies wat jy nodig het. Ons bevestig die res.',
  'This is an enquiry, not a checkout. The farm will personally confirm availability, collection, delivery and the final total.': 'Dit is ’n navraag, nie ’n aanlyn betaling nie. Die plaas sal beskikbaarheid, afhaal, aflewering en die finale totaal persoonlik bevestig.',
  'Your products': 'Jou produkte',
  'Continue shopping': 'Gaan voort met inkopies',
  'Your enquiry basket is empty.': 'Jou navraagmandjie is leeg.',
  'Browse farm products': 'Blaai deur plaasprodukte',
  'Estimated product total': 'Beraamde produktotaal',
  'Delivery, bulk quantities and current availability are confirmed before any order is final.': 'Aflewering, grootmaathoeveelhede en huidige beskikbaarheid word bevestig voordat enige bestelling finaal is.',
  'Send by WhatsApp': 'Stuur per WhatsApp',
  'Email alternative': 'E-pos-alternatief',
  'Tell us where to reply.': 'Sê vir ons waar om te antwoord.',
  'Full name': 'Volle naam',
  'Phone number': 'Telefoonnommer',
  'Email address': 'E-posadres',
  'How would you receive it?': 'Hoe wil jy dit ontvang?',
  'Not sure yet': 'Nog nie seker nie',
  'Suburb or area': 'Voorstad of gebied',
  'Anything we should know?': 'Enigiets wat ons moet weet?',
  'Preferred date, bulk quantity, garden project or questions…': 'Voorkeurdatum, grootmaathoeveelheid, tuinprojek of vrae…',
  'Send email enquiry': 'Stuur e-posnavraag',
  'Your details are used only to respond to this enquiry.': 'Jou besonderhede word slegs gebruik om op hierdie navraag te antwoord.',
  'Ordering information': 'Bestelinligting',
  'Simple orders. Personal confirmation.': 'Eenvoudige bestellings. Persoonlike bevestiging.',
  'The farm works with natural batches and bulky materials, so every enquiry is confirmed by a real person.': 'Die plaas werk met natuurlike sarsies en lywige materiaal, daarom word elke navraag deur ’n regte persoon bevestig.',
  'How it works': 'Hoe dit werk',
  'No anonymous checkout. No surprises.': 'Geen anonieme betaalblad nie. Geen verrassings nie.',
  'Build an enquiry online, send it by WhatsApp or email, and Nico will confirm what is ready and the most sensible way to receive it.': 'Stel ’n navraag aanlyn saam, stuur dit per WhatsApp of e-pos, en Nico sal bevestig wat gereed is en wat die verstandigste manier is om dit te ontvang.',
  'Build your enquiry': 'Stel jou navraag saam',
  'Choose products, bag sizes and quantities. The displayed total is an estimate based on the current website price list.': 'Kies produkte, sakgroottes en hoeveelhede. Die vertoonde totaal is ’n skatting volgens die huidige webwerfpryslys.',
  'Confirm availability': 'Bevestig beskikbaarheid',
  'The farm confirms stock, fresh-product timing and any bulk preparation required.': 'Die plaas bevestig voorraad, tydsberekening vir vars produkte en enige nodige grootmaatvoorbereiding.',
  'Arrange collection or delivery': 'Reël afhaal of aflewering',
  'Collection is from Montana, Pretoria by arrangement. Local delivery depends on area and order size.': 'Afhaal is volgens reëling in Montana, Pretoria. Plaaslike aflewering hang van die gebied en bestelgrootte af.',
  'Payment is arranged directly': 'Betaling word direk gereël',
  'No payment is taken on this website. Payment details are confirmed only after the order has been discussed.': 'Geen betaling word op hierdie webwerf geneem nie. Betalingsbesonderhede word eers bevestig nadat die bestelling bespreek is.',
  'Browse products': 'Blaai deur produkte',
  'Only what we need to reply.': 'Slegs wat ons nodig het om te antwoord.',
  'This website is designed to collect the minimum information required to answer an order or product enquiry.': 'Hierdie webwerf versamel slegs die minimum inligting wat nodig is om ’n bestelling- of produknavraag te beantwoord.',
  'Information you provide': 'Inligting wat jy verskaf',
  'How it is used': 'Hoe dit gebruik word',
  'WhatsApp and YouTube': 'WhatsApp en YouTube',
  'Questions or deletion': 'Vrae of verwydering',
  'When you send an email enquiry, the website may receive your name, telephone number, email address, suburb, fulfilment preference, enquiry basket and any note you add.': 'Wanneer jy ’n e-posnavraag stuur, kan die webwerf jou naam, telefoonnommer, e-posadres, voorstad, afhaal- of afleweringsvoorkeur, navraagmandjie en enige nota wat jy byvoeg ontvang.',
  'This information is used to answer your enquiry, confirm products and arrange collection or delivery. It is not used to create advertising profiles or sold to third parties.': 'Hierdie inligting word gebruik om jou navraag te beantwoord, produkte te bevestig en afhaal of aflewering te reël. Dit word nie vir advertensieprofiele gebruik of aan derde partye verkoop nie.',
  'If you choose WhatsApp or play embedded YouTube content, those services process information under their own privacy terms. The hero video uses YouTube’s privacy-enhanced embed mode and remains muted.': 'As jy WhatsApp kies of ingebedde YouTube-inhoud speel, verwerk daardie dienste inligting volgens hul eie privaatheidsvoorwaardes. Die heldevideo gebruik YouTube se privaatheidsverbeterde inbedmodus en bly gedemp.',
  'Contact nico@vermicompostfarm.co.za to ask about information submitted through the site or request its deletion.': 'Kontak nico@vermicompostfarm.co.za om navraag te doen oor inligting wat deur die webwerf ingedien is of om verwydering daarvan te versoek.',
  'Page not found': 'Bladsy nie gevind nie',
  '404 · Lost in the bedding': '404 · Verdwaal in die beddegoed',
  'This path has been composted.': 'Hierdie pad is gekomposteer.',
  'The page you followed is no longer here, but the useful material is still nearby.': 'Die bladsy waarna jy gegaan het, is nie meer hier nie, maar die nuttige materiaal is steeds naby.',
  'Return home': 'Gaan terug huis toe',
};

const english = Object.fromEntries(Object.entries(afrikaans).map(([en, af]) => [af, en]));

export const getLanguage = (): SiteLanguage => document.documentElement.lang === 'af' ? 'af' : 'en';
export const translate = (value: string, language = getLanguage()) => language === 'af' ? afrikaans[value] || value : english[value] || value;

const translateComposite = (value: string, language: SiteLanguage) => {
  const exact = translate(value, language);
  if (exact !== value) return exact;
  if (value.includes(' · ')) {
    const [label, ...rest] = value.split(' · ');
    return [translate(label, language), ...rest].join(' · ');
  }
  if (language === 'af' && value.endsWith(' on the farm')) return `${translate(value.slice(0, -12), language)} op die plaas`;
  if (language === 'en' && value.endsWith(' op die plaas')) return `${translate(value.slice(0, -13), language)} on the farm`;
  return value;
};

const replaceText = (root: ParentNode, language: SiteLanguage) => {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, { acceptNode(node) { return node.parentElement?.closest('script, style, noscript') ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT; } });
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  nodes.forEach((node) => { const raw = node.nodeValue || ''; const value = raw.trim(); const replacement = translateComposite(value, language); if (value && replacement !== value) node.nodeValue = raw.replace(value, replacement); });
  root.querySelectorAll<HTMLElement>('[placeholder], [aria-label], [title], [alt]').forEach((element) => ['placeholder', 'aria-label', 'title', 'alt'].forEach((attribute) => { const value = element.getAttribute(attribute); if (value) element.setAttribute(attribute, translateComposite(value, language)); }));
};

const updateButtons = (language: SiteLanguage) => document.querySelectorAll<HTMLButtonElement>('[data-language]').forEach((button) => button.setAttribute('aria-pressed', String(button.dataset.language === language)));

const updateLocalizedLinks = (language: SiteLanguage) => document.querySelectorAll<HTMLAnchorElement>('[data-whatsapp-contact]').forEach((link) => {
  const url = new URL(link.href);
  url.searchParams.set('text', language === 'af' ? 'Hallo Nico, ek het ’n vraag oor Vermicompost Farm.' : 'Hello Nico, I have a question about Vermicompost Farm.');
  link.href = url.toString();
});

const applyLanguage = (language: SiteLanguage, persist = true, announce = true) => {
  document.documentElement.lang = language;
  replaceText(document, language);
  updateButtons(language);
  updateLocalizedLinks(language);
  if (persist) { try { localStorage.setItem(STORAGE_KEY, language); } catch {} }
  if (announce) {
    document.dispatchEvent(new CustomEvent('language:changed', { detail: language }));
    queueMicrotask(() => { replaceText(document, language); updateButtons(language); });
  }
};

let initialLanguage: SiteLanguage = 'en';
try { initialLanguage = localStorage.getItem(STORAGE_KEY) === 'af' ? 'af' : 'en'; } catch {}
applyLanguage(initialLanguage, false, false);

document.addEventListener('click', (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('[data-language]'); if (button?.dataset.language === 'en' || button?.dataset.language === 'af') applyLanguage(button.dataset.language); });
document.addEventListener('basket:updated', () => queueMicrotask(() => replaceText(document, getLanguage())));
